# Intro to NumPy

In [4]:
import numpy as np

## Problem 1

In [60]:
def problem1():
    A = np.array( [ [3, -1, 4], [1, 5, -9] ] )
    B = np.array( [ [2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3] ] )
    prod = np.dot(A, B)
    return prod

In [61]:
problem1()

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

## Problem 2

In [57]:
def problem2():
    A = np.array( [ [3, 1, 4], [1, 5, 9], [-5, 3, 1] ] )
    A2 = np.dot(A, A)
    A3 = np.dot(A2, A)
    matrix = -1 * A3 + 9 * A2 - 15 * A
    return matrix

In [58]:
problem2()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Problem 3

In [70]:
def problem3():
    A = np.triu(np.ones((7, 7), dtype=np.int))
    B = np.tril(-1 * np.ones((7, 7), dtype=np.int)) + np.triu(5 * np.ones((7, 7), dtype=np.int)) + -5 * np.eye(7, dtype=int)
    prod = A @ B @ A
    matrix = prod.astype(np.int64)
    return matrix

In [71]:
problem3()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

## Problem 4

In [131]:
def problem4(x):
    xcop = np.copy(x)
    xcop[xcop < 0] = 0
    return xcop

In [181]:
x = np.array( [ [-1, -3, 4] ] )
problem4(x)

array([[0, 0, 4]])

## Problem 5

In [216]:
def problem5():
    A = np.arange(6).reshape((3,2)).T
    B = np.tril(3 * np.ones((3,3), dtype=np.int))
    C = -2 * np.eye(3, dtype=np.int)
    first = np.hstack((np.zeros(9).reshape(3,3), A.T, np.eye(3, dtype=np.int)))
    second = np.hstack((A, np.zeros(4).reshape(2,2), np.zeros(6).reshape(2,3)))
    third = np.hstack((B, np.zeros(6).reshape(3,2), C))
    matrix = np.vstack((first, second, third))
    matrix = matrix.astype(np.int)
    return matrix

In [217]:
problem5()

array([[ 0,  0,  0,  0,  1,  1,  0,  0],
       [ 0,  0,  0,  2,  3,  0,  1,  0],
       [ 0,  0,  0,  4,  5,  0,  0,  1],
       [ 0,  2,  4,  0,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0, -2,  0,  0],
       [ 3,  3,  0,  0,  0,  0, -2,  0],
       [ 3,  3,  3,  0,  0,  0,  0, -2]])

## Problem 6

In [178]:
def problem6(x):
    sum = x.sum(axis=1).reshape(3,1)
    ans = x / sum
    return ans

In [187]:
x = np.arange(9).reshape((3,3))
problem6(x)

array([[0.        , 0.33333333, 0.66666667],
       [0.25      , 0.33333333, 0.41666667],
       [0.28571429, 0.33333333, 0.38095238]])

## Problem 7

In [218]:
def problem7():
    grid = np.load("grid.npy")
    hori = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    vert = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    rdiag = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
    ldiag = np.max(grid[:-3,3:] * grid[1:-2,2:-1] * grid[2:-1,1:-2] * grid[3:,:-3])
    answer = np.max( [hori, vert, rdiag, ldiag ] )
    return answer

In [220]:
problem7()

70600674

# Standard Library

In [221]:
def problem1(L):
    return (min(L), max(L), sum(L) / len(L))

In [223]:
L = [1, 2, 3, 4]
problem1(L)

(1, 4, 2.5)

## Problem 2

In [230]:
int_1 = 3
int_2 = int_1
int_2 += 1
int_1 == int_2

False

In [233]:
str_1 = "hello"
str_2 = str_1
str_2 = str_2 + " world"
str_1 == str_2

False

In [234]:
list_1 = [1, "hi", 3]
list_2 = list_1
list_2[0] = 17
list_1 == list_2

True

In [237]:
tuple_1 = (4, 8)
tuple_2 = tuple_1
tuple_2 += (1,4)
tuple_1 == tuple_2

False

In [238]:
set_1 = {"hi", "hello", 3}
set_2 = set_1
set_1.add(17)
set_1 == set_2

True

In [240]:
print("The following data types are mutable: list, set. The following data types are immutable: int, str, tuple.")

The following data types are mutable: list, set. The following data types are immutable: int, str, tuple.


## Problem 3

In [1]:
import calculator as calc

In [8]:
def problem3(len1, len2):
    return calc.sqrt(calc.sum(calc.prod(len1, len1), calc.prod(len2, len2)))

In [9]:
problem3(3, 4)

5.0

## Problem 4

In [3]:
from itertools import combinations

In [33]:
def problem4(A):
    ans = []
    for i in range(len(A) + 1):
        for combo in list(combinations(A, i)):
            ans.append(set(combo))
    return ans

In [35]:
A = {"a", "b", "c"}
problem4(A)

[set(),
 {'b'},
 {'a'},
 {'c'},
 {'a', 'b'},
 {'b', 'c'},
 {'a', 'c'},
 {'a', 'b', 'c'}]

# Unit Testing

In [3]:
def smallest_factor(n):
    """Return the smallest prime factor of the positive integer n."""
    if n == 1: return 1
    for i in range(2, int(n**.5)):
        if n % i == 0: return i
    return n

In [ ]:
def test_smallest_factor():
    